# Generated by Django 3.0 on 2019-12-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='queestion_text',
            new_name='question_text',
        ),
    ]
